# Generated by Django 6.0.3 on 2026-05-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_privacy',
            field=models.CharField(choices=[('everyone', 'Все пользователи'), ('members_only', 'Только участники чатов'), ('no_one', 'Никто (кроме администраторов)')], default='members_only', max_length=20, verbose_name='Кто видит email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_privacy',
            field=models.CharField(choices=[('everyone', 'Все пользователи'), ('members_only', 'Только участники чатов'), ('no_one', 'Никто (кроме администраторов)')], default='members_only', max_length=20, verbose_name='Кто видит телефон'),
        ),
    ]
