# Generated by Django 6.0.5 on 2026-05-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='font_family',
            field=models.CharField(choices=[('system', 'Системный'), ('sans-serif', 'Без засечек (Arial)'), ('serif', 'С засечками (Georgia)'), ('roboto', 'Roboto'), ('inter', 'Inter'), ('monospace', 'Моноширинный')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='font_size',
            field=models.IntegerField(default=16, help_text='14–22 px'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('fire', 'Огненная (тёплая)'), ('high_contrast', 'Высокий контраст'), ('sepia', 'Сепия (для глаз)')], default='light', max_length=20),
        ),
    ]
