# Generated by Django 6.0.5 on 2026-05-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userpreferences_font_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('high_contrast', 'Высокий контраст'), ('sepia', 'Сепия (для глаз)')], default='light', max_length=20),
        ),
    ]
