# Generated by Django 6.0.5 on 2026-05-12 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_phone'),
        ('users', '0006_alter_userpreferences_theme'),
    ]

    operations = [
    ]
