# Generated by Django 6.0.5 on 2026-05-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20260513_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('fire', 'Пламя'), ('sepia', 'Сепия (для глаз)')], default='light', max_length=20),
        ),
    ]
