# Generated by Django 6.0.5 on 2026-05-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userpreferences_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='font_family',
            field=models.CharField(choices=[('system', 'Системный'), ('sans-serif', 'Arial'), ('serif', 'Georgia'), ('roboto', 'Roboto'), ('inter', 'Inter'), ('monospace', 'Моноширинный')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('fire', 'Пламя'), ('sepia', 'Сепия')], default='light', max_length=20),
        ),
    ]
