# Generated by Django 6.0.5 on 2026-05-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='_text',
            field=models.TextField(db_column='text', default=1),
            preserve_default=False,
        ),
    ]
