# Generated by Django 6.0.5 on 2026-05-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_text_message__text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='_text',
            field=models.TextField(db_column='text', max_length=2000),
        ),
    ]
