# Generated by Django 6.0.5 on 2026-05-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message__text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='_text',
            field=models.TextField(db_column='text'),
        ),
    ]
