# Generated by Django 6.0.5 on 2026-05-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_attachment_file_type_attachment_original_name_and_more'),
        ('chat', '0004_alter_message__text'),
    ]

    operations = [
    ]
