# Generated by Django 6.0.5 on 2026-05-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_merge_20260513_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='_text',
            field=models.TextField(db_column='text'),
        ),
    ]
